---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework # имя CRD должно иметь формат plural.group
spec:
  scope: Namespaced     # Данный CRD будер работать в рамках namespace
  group: otus.homework  # Группа, отражается в поле apiVersion CR
  versions:             # Список версий
    - name: v1
      served: true      # Будет ли обслуживаться API-сервером данная версия
      storage: true     # Фиксирует  версию описания, которая будет сохраняться в etcd
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                database:
                  type: string
                  description: database name
                image:
                  type: string
                  description: image for MySQL
                password:
                  type: string
                  description: password for DB
                storage_size:
                  type: string
                  description: storage size
              required:
              - image
              - database
              - password
              - storage_size
            # назначение ключа объекта yaml .status (пустой объект)
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
  names:                # различные форматы имени объекта CR
    kind: MySQL         # kind CR
    plural: mysqls      
    singular: mysql
    shortNames:
      - ms
...
